sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t levonbaghdasaryan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true levonbaghdasaryan/docker-react npm run test